USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_CHUYENNHANVIEN]    Script Date: 5/25/2022 3:14:07 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_CHUYENNHANVIEN] @MANV NCHAR(10), @MACN NCHAR(10), @MANVMOI NCHAR(10)
AS
DECLARE @LGNAME NVARCHAR(50)
DECLARE @USERNAME NVARCHAR(50)
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN
	BEGIN DISTRIBUTED TRANSACTION
		DECLARE @HO NVARCHAR(40)
		DECLARE @TEN NVARCHAR(10)
		DECLARE @DIACHI NVARCHAR(100)
		DECLARE @PHAI NCHAR(3)
		DECLARE @SODT NVARCHAR(15)
		DECLARE @NEWMANV NCHAR(10)

		SELECT @HO = HO,  @TEN = TEN, @DIACHI = DIACHI, @PHAI = PHAI, @SODT = SODT FROM NhanVien WHERE MANV = @MANV
		-- Nếu tồn tại thì đổi trạng thái
		IF EXISTS(SELECT MANV FROM LINK1.NGANHANG.dbo.NhanVien WHERE HO = @HO AND TEN = @TEN AND DIACHI = @DIACHI AND PHAI = @PHAI AND SODT = @SODT)
		BEGIN
			UPDATE LINK1.NGANHANG.dbo.NhanVien
			SET TrangThaiXoa = 0
			WHERE MANV = (SELECT MANV FROM LINK1.NGANHANG.dbo.NhanVien WHERE HO = @HO AND TEN = @TEN AND DIACHI = @DIACHI AND PHAI = @PHAI AND SODT = @SODT)
		END
		ELSE
		-- Nếu chưa tồn tại thì thêm vào bằng cách lấy MANVMOI
		BEGIN
			INSERT INTO LINK1.NGANHANG.dbo.NhanVien (MANV, HO, TEN, DIACHI, PHAI, SODT, MACN, TrangThaiXoa)
			VALUES (@MANVMOI, @HO, @TEN, @DIACHI, @PHAI, @SODT, @MACN, 0) 
		END
		UPDATE dbo.NhanVien
		SET TrangThaiXoa = 1
		WHERE MANV = @MANV
	COMMIT TRANSACTION
		-- Kiểm tra xem Nhân Viên đã có login chưa, có thì xóa
		IF EXISTS(SELECT SUSER_SNAME(SID) FROM SYS.SYSUSERS WHERE NAME = CAST(@MANV AS NVARCHAR))
		BEGIN
			SET @LGNAME = CAST((SELECT SUSER_SNAME(SID) FROM SYS.SYSUSERS WHERE NAME = CAST(@MANV AS NVARCHAR)) AS VARCHAR(50))
			SET @USERNAME = CAST(@MANV AS VARCHAR(50))
			EXEC SP_DROPUSER @USERNAME
			EXEC SP_DROPLOGIN @LGNAME
		END
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_DANGNHAP]    Script Date: 5/25/2022 3:14:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_DANGNHAP]
	@TENLOGIN NVARCHAR( 100)
AS
	DECLARE @UID INT
	DECLARE @MANV NVARCHAR(100)
	SELECT @UID= uid , @MANV= NAME FROM sys.sysusers 
  	WHERE sid = SUSER_SID(@TENLOGIN)

	SELECT  MAGV= @MANV, 
       		HOTEN = (SELECT HO+ ' '+TEN FROM dbo.NHANVIEN WHERE MANV=@MANV ), 
       		TENNHOM=NAME
  	FROM sys.sysusers
    	WHERE UID = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=@uid)

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_DANHSACHKHACHHANG]    Script Date: 5/25/2022 3:15:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_DANHSACHKHACHHANG]
AS
SELECT HO, TEN, CMND, DIACHI, PHAI, SODT, MACN
FROM KhachHang

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_DANHSACHNHANVIEN]    Script Date: 5/25/2022 3:15:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_DANHSACHNHANVIEN]
AS
SELECT MANV, HO, TEN, DIACHI, PHAI, SODT, MACN, TrangThaiXoa
FROM NhanVien

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_DANHSACHNHANVIENCHUADANGKY]    Script Date: 5/25/2022 3:15:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--DANH SÁCH NHÂN VIÊN CHƯA ĐĂNG KÍ
ALTER PROC [dbo].[SP_DANHSACHNHANVIENCHUADANGKY]
AS
SELECT MANV, HO + ' ' + TEN AS HOTEN, DIACHI, PHAI, SODT 
FROM NhanVien WHERE NOT EXISTS (SELECT 1 FROM SYS.sysusers WHERE name = MANV) AND TrangThaiXoa = 0

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_GIAODICHCHUYENTIEN]    Script Date: 5/25/2022 3:15:39 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_GIAODICHCHUYENTIEN]
	@SOTK_NHAN NCHAR(9), @SOTK_CHUYEN NCHAR(9), @SOTIEN MONEY, @MANV NCHAR(10)
AS
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
BEGIN TRY
	IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK_CHUYEN)
		BEGIN
			UPDATE dbo.TaiKhoan
			SET SODU = SODU - @SOTIEN
			WHERE SOTK = @SOTK_CHUYEN
		END
	IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK_NHAN)
		BEGIN
			UPDATE dbo.TaiKhoan
			SET SODU = SODU + @SOTIEN
			WHERE SOTK = @SOTK_NHAN
		END
	IF EXISTS(SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
		BEGIN
			INSERT INTO dbo.GD_CHUYENTIEN(SOTK_CHUYEN,NGAYGD,SOTIEN,SOTK_NHAN,MANV)
				   VALUES(@SOTK_CHUYEN, GETDATE(), @SOTIEN, @SOTK_NHAN, @MANV)
		END
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF (@@TRANCOUNT > 0)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR('Lỗi khi chuyển tiền. Vui lòng kiểm tra.', 16, 1)
	END
END CATCH

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_GIAODICHGUIRUT]    Script Date: 5/25/2022 3:15:47 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_GIAODICHGUIRUT]
@TYPE NCHAR(2), @SOTIEN MONEY, @SOTK NCHAR(9), @MANV NCHAR(10)
AS
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
BEGIN TRY
	IF(@TYPE = 'GT')
		BEGIN
			IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK)
				BEGIN
					UPDATE dbo.TaiKhoan
					SET SODU = SODU + @SOTIEN
					WHERE SOTK = @SOTK
				END
		END
	IF(@TYPE = 'RT')
		BEGIN
			IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK)
				BEGIN
					UPDATE dbo.TaiKhoan
					SET SODU = SODU - @SOTIEN
					WHERE SOTK = @SOTK
				END
		END
	IF EXISTS(SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
		BEGIN
			INSERT INTO dbo.GD_GOIRUT(SOTK, LOAIGD, NGAYGD, SOTIEN, MANV)
				   VALUES(@SOTK, @TYPE, GETDATE(), @SOTIEN, @MANV)
		END
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF (@@TRANCOUNT > 0)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR('Lỗi khi gởi rút tiền. Vui lòng kiểm tra.', 16, 1)
	END
END CATCH

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_KIEMTRAKHACHHANG]    Script Date: 5/25/2022 3:16:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_KIEMTRAKHACHHANG]
	@CMND NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT CMND FROM dbo.KhachHang WHERE dbo.KhachHang.CMND = @CMND)
		RETURN 1
	IF EXISTS(SELECT CMND FROM LINK2.NGANHANG.dbo.KhachHang KH WHERE KH.CMND = @CMND)
		RETURN 2  
	RETURN 0 
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_KIEMTRANHANVIEN]    Script Date: 5/25/2022 3:16:52 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_KIEMTRANHANVIEN]
	@MANV NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
	IF EXISTS(SELECT NV.MANV FROM LINK0.NGANHANG.dbo.NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
	RETURN 0
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_KIEMTRASOTK]    Script Date: 5/25/2022 3:17:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_KIEMTRASOTK]
	@SOTK NCHAR(9)
AS
BEGIN
	IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK)
		RETURN 1
	ELSE RETURN 0
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[sp_KIEMTRATAIKHOANKHACHHANG]    Script Date: 5/25/2022 3:17:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_KIEMTRATAIKHOANKHACHHANG]
	@CMND NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.CMND = @CMND)
		RETURN 1
	ELSE RETURN 0
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_LIETKECACTAIKHOANMOTRONGMOTKHOANTHOIGIANCUACHINHANH]    Script Date: 5/25/2022 3:17:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_LIETKECACTAIKHOANMOTRONGMOTKHOANTHOIGIANCUACHINHANH]
	@NGAYBD DATETIME,
	@NGAYKT DATETIME,
	@MACN NCHAR(10)
AS
BEGIN
	IF @MACN = 'HAICN'
		BEGIN
			SELECT SOTK, CMND, SODU, NGAYMOTK,MACN
			FROM TaiKhoan
			WHERE NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT
		END
	ELSE
		BEGIN
			SELECT SOTK, CMND, SODU, NGAYMOTK,MACN
			FROM TaiKhoan
			WHERE (NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT) AND (MACN = @MACN)
		END
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_LIETKEKHACHHANGTHEOTUNGCHINHANH]    Script Date: 5/25/2022 3:17:52 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_LIETKEKHACHHANGTHEOTUNGCHINHANH]
AS
BEGIN
	SELECT HO, TEN, CMND, NGAYCAP, SODT, DIACHI
	FROM KhachHang
	ORDER BY HO, TEN
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_SAOKEGIAODICHMOTTAIKHOANTRONGMOTKHOANTHOIGIAN]    Script Date: 5/25/2022 3:18:02 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_SAOKEGIAODICHMOTTAIKHOANTRONGMOTKHOANTHOIGIAN]
	@SOTAIKHOAN NVARCHAR(9), @NGAYBD DATETIME, @NGAYKT DATETIME
AS
DECLARE @SOTIENBANDAU MONEY, @SODU MONEY
DECLARE @tab table(SODUDAU MONEY, NGAYGD DATETIME, LOAIGD NVARCHAR(2), SOTIEN MONEY, SODUSAU MONEY)
DECLARE @tabGD table(NGAYDG DATETIME, LOAIGD NVARCHAR(2), SOTIEN MONEY, SOTK NCHAR(9))

SELECT @SODU = SODU FROM TaiKhoan TK WHERE TK.SOTK = @SOTAIKHOAN


SELECT @SOTIENBANDAU = @SODU + SUM(CASE WHEN GD.LOAIGD = 'RT' THEN GD.SOTIEN WHEN GD.LOAIGD = 'GT' THEN -GD.SOTIEN
WHEN GD.SOTK = @SOTAIKHOAN THEN -GD.SOTIEN ELSE GD.SOTIEN END)
FROM (SELECT NGAYGD, SOTIEN, LOAIGD='CT', SOTK = CT.SOTK_NHAN  FROM LINK0.NGANHANG.DBO.GD_CHUYENTIEN CT WHERE CT.SOTK_NHAN = @SOTAIKHOAN OR CT.SOTK_CHUYEN = @SOTAIKHOAN
UNION SELECT NGAYGD, SOTIEN, LOAIGD, SOTK FROM LINK0.NGANHANG.DBO.GD_GOIRUT WHERE GD_GOIRUT.SOTK = @SOTAIKHOAN) GD
WHERE GD.NGAYGD >= @NGAYBD
 
DECLARE @SODUDAU MONEY, @NGAYGD DATETIME, @LOAIGD NVARCHAR(2), @SOTIEN MONEY, @SODUSAU MONEY, @TK_NHAN NVARCHAR(9), @TEMP MONEY
DECLARE cursorTK CURSOR 
FOR SELECT GD.NGAYGD, GD.LOAIGD, GD.SOTIEN, GD.SOTK
	FROM (SELECT NGAYGD, SOTIEN, LOAIGD='CT', SOTK = CT.SOTK_NHAN  FROM LINK0.NGANHANG.DBO.GD_CHUYENTIEN CT WHERE CT.SOTK_NHAN = @SOTAIKHOAN OR CT.SOTK_CHUYEN = @SOTAIKHOAN
	UNION SELECT NGAYGD, SOTIEN, LOAIGD, SOTK FROM LINK0.NGANHANG.DBO.GD_GOIRUT WHERE GD_GOIRUT.SOTK = @SOTAIKHOAN) GD
	Where GD.NGAYGD BETWEEN @NGAYBD AND @NGAYKT
	ORDER BY GD.NGAYGD


OPEN cursorTK
FETCH NEXT FROM cursorTK
      INTO @NGAYGD, @LOAIGD, @SOTIEN, @TK_NHAN
SET @SODUDAU = @SOTIENBANDAU
IF(@LOAIGD = 'RT')
			SET @SODUSAU = @SODUDAU - @SOTIEN
	ELSE IF(@LOAIGD = 'GT')
			SET @SODUSAU = @SODUDAU + @SOTIEN
	ELSE IF(@TK_NHAN = @SOTAIKHOAN)
			SET @SODUSAU = @SODUDAU + @SOTIEN
	ELSE
			SET @SODUSAU = @SODUDAU - @SOTIEN
WHILE @@FETCH_STATUS = 0
BEGIN 
	SET @TEMP = @SODUSAU   
	INSERT INTO @tab(SODUDAU, NGAYGD, LOAIGD, SOTIEN, SODUSAU)
	VALUES (@SODUDAU, @NGAYGD, @LOAIGD, @SOTIEN, @SODUSAU) 
	FETCH NEXT FROM cursorTK
      INTO @NGAYGD, @LOAIGD, @SOTIEN, @TK_NHAN
	
	SET @SODUDAU = @TEMP
	IF(@LOAIGD = 'RT')
			SET @SODUSAU = @TEMP - @SOTIEN
	ELSE IF(@LOAIGD = 'GT')
			SET @SODUSAU = @TEMP + @SOTIEN
	ELSE IF(@TK_NHAN = @SOTAIKHOAN)
			SET @SODUSAU = @TEMP + @SOTIEN
	ELSE
			SET @SODUSAU = @TEMP - @SOTIEN
END
SELECT SODUDAU, NGAYGD,(CASE WHEN (LOAIGD = 'CT' AND SODUSAU < SODUDAU) THEN N'CHUYỂN TIỀN' WHEN (LOAIGD = 'CT' AND SODUSAU > SODUDAU) THEN N'NHẬN TIỀN' WHEN LOAIGD = 'GT' THEN N'GỞI TIỀN' ELSE N'RÚT TIỀN' END) AS LOAIGD, SOTIEN, SODUSAU
FROM @tab t
CLOSE cursorTK  
DEALLOCATE cursorTK  

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_LIETKECACTAIKHOANMOTRONGMOTKHOANTHOIGIANCUACHINHANH]    Script Date: 5/25/2022 3:17:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_LIETKECACTAIKHOANMOTRONGMOTKHOANTHOIGIANCUACHINHANH]
	@NGAYBD DATETIME,
	@NGAYKT DATETIME,
	@MACN NCHAR(10)
AS
BEGIN
	IF @MACN = 'HAICN'
		BEGIN
			SELECT SOTK, CMND, SODU, NGAYMOTK,MACN
			FROM TaiKhoan
			WHERE NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT
		END
	ELSE
		BEGIN
			SELECT SOTK, CMND, SODU, NGAYMOTK,MACN
			FROM TaiKhoan
			WHERE (NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT) AND (MACN = @MACN)
		END
END

GO

USE [NGANHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_TAOTAIKHOAN]    Script Date: 5/25/2022 3:18:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[SP_TAOTAIKHOAN]
    @LGNAME VARCHAR(50),  @PASS VARCHAR(50),
    @USERNAME VARCHAR(50),  @ROLE VARCHAR(50)     
AS
    DECLARE @RET INT
    EXEC @RET= SP_ADDLOGIN @LGNAME, @PASS, 'NGANHANG'
    IF (@RET =1)  -- LOGIN NAME BI TRUNG
    BEGIN
        RAISERROR ('Login name bị trùng', 16, 1)
        RETURN
    END 
    EXEC @RET= SP_GRANTDBACCESS @LGNAME, @USERNAME
    IF (@RET =1)  -- USER  NAME BI TRUNG
    BEGIN
        EXEC SP_DROPLOGIN @LGNAME
        RAISERROR ('Nhân viên đã có login name', 16, 2)
        RETURN
    END
    EXEC sp_addrolemember @ROLE, @USERNAME
    IF @ROLE = N'NganHang'
    BEGIN
        EXEC sp_addsrvrolemember @LGNAME, 'SecurityAdmin'
        EXEC sp_addsrvrolemember @LGNAME, 'ProcessAdmin'
    END
    IF @ROLE = N'ChiNhanh'
    BEGIN
        EXEC sp_addsrvrolemember @LGNAME, 'SecurityAdmin'
        EXEC sp_addsrvrolemember @LGNAME, 'ProcessAdmin'
    END

